#!/usr/bin/env bash
# Upgrade disposable 0.x state without deleting source or existing output files.
set -euo pipefail
script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
repo_root=$(cd -- "$script_dir/.." && pwd)
source "$script_dir/toolchain.sh"
source "$script_dir/worker.sh"
dart_bin=$(resolve_toolchain_dart)
pub_cache=$(resolve_toolchain_pub_cache)
temporary_dir=$(mktemp -d)
trap 'status=$?; if ((status == 0)); then rm -rf -- "$temporary_dir"; else printf "upgrade: retained %s\n" "$temporary_dir" >&2; fi' EXIT
worker_ensure_frontend
worker_prepare
worker_attach "$temporary_dir/workspace"
for lane in stock rust; do
  fixture="$temporary_dir/workspace/fixtures/$lane"
  mkdir -p "$fixture"
  cp "$repo_root/fixtures/json_serializable_app/pubspec.yaml" "$repo_root/fixtures/json_serializable_app/pubspec.lock" "$fixture/"
  cp -R "$repo_root/fixtures/json_serializable_app/lib" "$fixture/"
  worker_pub_get "$fixture" --offline
done
stock="$temporary_dir/workspace/fixtures/stock"
native="$temporary_dir/workspace/fixtures/rust"
export BUILD_RUNNER_ACCELERATOR_CACHE="$temporary_dir/cache"
export BUILD_RUNNER_ACCELERATOR_WORKER_AOT=0
stock_build() {
  verification_run_stock_build "$stock" build/upgrade-stock "$temporary_dir/stock.log" "$dart_bin" "$pub_cache" build --delete-conflicting-outputs
}
native_build() {
  VERIFY_COMMAND_LOG="$temporary_dir/$1.log" VERIFY_WORKSPACE="$native" worker_run_frontend build --root "$native" --dart "$dart_bin" --mode rust
}
compare() {
  python3 - "$stock/lib" "$native/lib" <<'PY'
from pathlib import Path
import sys
roots = [Path(p) for p in sys.argv[1:]]
outputs = [{str(p.relative_to(root)): p.read_bytes() for p in root.rglob('*.g.dart')} for root in roots]
assert outputs[0] and outputs[0] == outputs[1], 'stock/native generated bytes differ'
PY
}
stock_build
native_build clean
compare
state="$native/.dart_tool/build_runner_accelerator"
# Populate real old manifest fields and an obsolete JSON graph at the active path.
python3 - "$state" "$temporary_dir/cache" <<'PY'
from pathlib import Path
import json, sys
state, cache = map(Path, sys.argv[1:])
path = state/'builder-manifest.json'
manifest = json.loads(path.read_text())
manifest['version'] = 8
for entry in manifest['builders'] + manifest['definitions']:
    if entry.get('extensions'):
        entry.update(entry.pop('extensions')[0])
path.write_text(json.dumps(manifest))
(state/'graph-v3.bin').write_text('{"schema_version":1,"actions":{}}')
# These earlier shared namespaces must remain untouched and unselected.
for name in ['byte_store/old-fingerprint/ab/ab.linked', 'dep_parse/v1-old/key.json', 'dep_parse/v2-old/store.bin']:
    path = cache/name
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(b'old-cache-sentinel')
(state/'user-sentinel').write_text('keep')
PY
native_build upgrade
compare
grep -Fq 'invalidating graph' "$temporary_dir/upgrade.log"
python3 - "$state" "$temporary_dir/cache" <<'PY'
from pathlib import Path
import json, sys
state, cache = map(Path, sys.argv[1:])
manifest = json.loads((state/'builder-manifest.json').read_text())
assert manifest['version'] == 9
assert all('input_suffix' not in b and 'output_suffixes' not in b for b in manifest['builders'] + manifest['definitions'])
assert (state/'graph-v3.bin').read_bytes().startswith(b'BRAG')
assert (state/'user-sentinel').read_text() == 'keep'
for name in ['byte_store/old-fingerprint/ab/ab.linked', 'dep_parse/v1-old/key.json', 'dep_parse/v2-old/store.bin']:
    assert (cache/name).read_bytes() == b'old-cache-sentinel'
assert list((cache/'byte_store'/'v2').rglob('*.index'))
PY
native_build noop
compare
grep -Fq 'No work to do (Rust frontend)' "$temporary_dir/noop.log"
# A real source edit exercises regenerated graph dependency tracking.
python3 - "$native/lib/model.dart" "$stock/lib/model.dart" <<'PY_EDIT'
from pathlib import Path
import sys
for name in sys.argv[1:]:
    path = Path(name)
    path.write_text(path.read_text().replace('final int id;', 'final num id;'))
PY_EDIT
stock_build
native_build incremental
compare
# The retained diagnostic alternative rebuilds in a separate namespace.
printf '{}' > "$state/graph-v3.bin"
BUILD_RUNNER_ACCELERATOR_PACKED_STORE=0 native_build per-key
compare
[[ -d "$temporary_dir/cache/byte_store/per-key-v1" ]]
# Fail mismatched custom workers before any output/graph can be committed.
cp "$state/graph-v3.bin" "$temporary_dir/graph.before"
printf '\n// force worker validation\n' >> "$native/lib/model.dart"
for problem in wrong-version missing-version wrong-protocol missing-capability; do
  python3 - "$temporary_dir/custom.dart" "$problem" <<'PY_WORKER'
from pathlib import Path
import sys
path, problem = sys.argv[1:]
version = "'accelerator_version': buildRunnerAcceleratorVersion,"
if problem == 'wrong-version': version = "'accelerator_version': '0.0.0',"
if problem == 'missing-version': version = ''
wire = 2 if problem == 'wrong-protocol' else 1
capabilities = ['asset-rpc-binary-read-v1', 'build-result-binary-v1', 'shared-blocked-assets-v1', 'reset-overlay-blob-v1']
if problem == 'missing-capability': capabilities.remove('reset-overlay-blob-v1')
Path(path).write_text("""import 'dart:io';
import 'package:build_runner_accelerator/src/protocol.dart';
import 'package:build_runner_accelerator/src/frontend_binary_resolver.dart' show buildRunnerAcceleratorVersion;
Future<void> main() async {
  final request = await FrameReader(stdin).next();
  await FrameWriter(stdout).send({
""" + f"'v': {wire}, 'type': 'initialized', 'id': request!['id'], {version} 'capabilities': {capabilities}" + """});
}
""")
PY_WORKER
  if VERIFY_COMMAND_LOG="$temporary_dir/$problem.log" VERIFY_WORKSPACE="$native" worker_run_frontend build --root "$native" --dart "$dart_bin" --mode rust --worker "$temporary_dir/custom.dart"; then
    printf 'upgrade: invalid custom worker accepted: %s\n' "$problem" >&2; exit 1
  fi
  case "$problem" in
    wrong-version|missing-version) grep -Fq 'accelerator_version mismatch' "$temporary_dir/$problem.log" ;;
    wrong-protocol) grep -Fq 'unsupported or missing IPC protocol version' "$temporary_dir/$problem.log" ;;
    missing-capability) grep -Fq 'reset-overlay-blob-v1' "$temporary_dir/$problem.log" ;;
  esac
  compare
  cmp "$temporary_dir/graph.before" "$state/graph-v3.bin"
done
cp "$stock/lib/model.dart" "$native/lib/model.dart"
# CLI alias removal must also be explicit on the native parser.
if VERIFY_COMMAND_LOG="$temporary_dir/alias.log" VERIFY_WORKSPACE="$native" worker_run_frontend aot-prewarm --root "$native" --mode dart; then
  printf 'upgrade: old alias unexpectedly succeeded\n' >&2; exit 1
fi
grep -Fq 'aot-prewarm was removed; use prewarm' "$temporary_dir/alias.log"
printf 'upgrade: PASS old-state/clean/noop/incremental/per-key/worker-validation stock bytes preserved\n'
