#!/usr/bin/env python3
"""Prepare a disposable Riverpod fixture with many actions sharing sources.

Resolve pub dependencies and prepare native/AOT workers separately, outside
timing. benchmark_cold_build.py --fixture-kind riverpod-shared --stock-check
compares real provider-name edits and all generated bytes with stock.
"""
import argparse
from pathlib import Path
import shutil


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--root', type=Path, required=True)
    parser.add_argument('--ordinary-imports', action='store_true',
                        help='Only ordinary imports; Analyzer may avoid subsequent shared reads')
    args = parser.parse_args()
    repo = Path(__file__).resolve().parent.parent
    root = args.root.resolve()
    root.mkdir(parents=True, exist_ok=False)
    fixture = repo / 'fixtures/riverpod_app'
    for name in ('pubspec.yaml', 'pubspec.lock', 'build.yaml'):
        if (fixture / name).exists():
            shutil.copy2(fixture / name, root / name)
    pubspec = root / 'pubspec.yaml'
    pubspec.write_text(pubspec.read_text().replace('path: ../..', f'path: {repo}'))
    lib = root / 'lib'
    lib.mkdir()
    # Ordinary Dart declarations, rather than comment padding. All 24 entry
    # points share eight API libraries, as well as the generator closure.
    # Conditional alternatives force collector visibility reads each action;
    # ordinary imports exercise the Analyzer's existing graph reuse instead.
    for n in range(8):
        content = ''.join(
            f'class Shared{n}Type{k} {{\n'
            f'  const Shared{n}Type{k}(this.value);\n'
            '  final int value;\n'
            '  int scaled(int factor) => value * factor;\n}\n'
            for k in range(256))
        (lib / f'shared_{n}.dart').write_text(content)
        if not args.ordinary_imports:
            (lib / f'shared_{n}_io.dart').write_text(content.replace(
                'value * factor', 'factor * value'))
    for n in range(24):
        (lib / f'provider_{n:02}.dart').write_text(
            "import 'package:riverpod_annotation/riverpod_annotation.dart';\n" +
            ''.join(f"import 'shared_{k}.dart'" +
                    ('' if args.ordinary_imports else
                     f" if (dart.library.io) 'shared_{k}_io.dart'") + ';\n'
                    for k in range(8)) +
            f"part 'provider_{n:02}.g.dart';\n@riverpod\nint answer{n}(Ref ref) => " +
            ' + '.join(f'Shared{k}Type0({n}).value' for k in range(8)) + ';\n')


if __name__ == '__main__':
    main()
